# Travis-CI Build for bee2
# see travis-ci.org for details

language: c
sudo: false

compiler:
  - gcc
  - clang

branches:
  only:
    - master

script: 
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Coverage .. && make && make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
