# Travis-CI Build for bee2
# see travis-ci.org for details

language: c

sudo: false

branches:
  only:
    - master

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Coverage
  - BUILD_TYPE=ASan
  - BUILD_TYPE=MemSan
  - BUILD_TYPE=CheckFull

script: 
  - mkdir build && cd build
  - cmake -DBUILD_TYPE=$BUILD_TYPE ..
  - make
  - make test
  - sudo make install
