# Travis-CI Build for bee2
# see travis-ci.org for details

language: c

sudo: required

branches:
  only:
    - master

env:
  global:
    - secure: "rBbnGfVs2g9bhAIX6hAjQMKfqT4dTEaa65sMmAp3EJUT9VVtRiRb7EtlsIy9IwLXx4w15a/myGMhDynGWzLvV+ydcKzhMgvT3dIhWm/J4noPFXT+fSPXcnAS1gPyhuMIk1cuyn5TRmvaXokihEeril/6wUHXDsfhrdMwl3A2D+OTqdaDgwj2wbTHfgmOq0uQzVBD6l3YtnmLAzo2/hdOteyy+FbWN3bjLOReh3+Xfuj2llj9OGeaSFvOe/6MASx0rkqznQ1s3t4I8Id1P9athgP51RvDFJAeY3NXPgMNAGwYObkpAz5Vywz/abX09xiDZOt4MSC+iXuKmK4OcOthrHv8CoQqnUxrCiq3hGxg+kQkAeqFuQA+iKAD3If550ABGN6AB8/uie3TZHAE6jMnHRld+ob9qvIASHbAMeIpITadqu9ceMSap5LK28zV2czSyKd2h9J2bHt3wHm5U4goP0mmV4A2LGcAH7Yo1ysl/VEYTLGrebGM0ugw2ulI+rmMxVrDEGZ8GHP7TS8mCa9lalE1HoiHkhlu0dyyFjqcLZOQGNaUykSqZjDM1v953gtOqZ2suMXnFhSSGjnlUtJrszWV22OgjNA35d2/fc2P1sMboc71zUnUVycPPy9KtyFOFuYxFWiGc23Z49KPZbbO+gYQFvuhUcpx9rPBKEEd524="

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release BUILD_FAST=OFF
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Debug BUILD_FAST=ON
    - os: osx
      compiler: gcc
      env: BUILD_TYPE=ASan BUILD_FAST=OFF
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Check BUILD_FAST=ON
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Coverage BUILD_FAST=OFF

addons:
  coverity_scan:
    project:
      name: "agievich/bee2"
      description: "Build submitted via Travis CI"
    notification_email: agievich@gmail.com
    build_command_prepend: mkdir coverity && cd coverity && cmake -DBUILD_TYPE=Debug -DBUILD_FAST=OFF ..
    build_command: make
    branch_pattern: master

script: 
  - mkdir build && cd build 
  - cmake -DBUILD_TYPE=$BUILD_TYPE -DBUILD_FAST=$BUILD_FAST ..
  - make
  - make test
  - sudo make install

after_success:
  - if [ "$BUILD_TYPE" == "Coverage"]; then
      bash <(curl -s https://codecov.io/bash)
    fi