# Travis-CI Build for bee2
# see travis-ci.org for details

language: c

branches:
  only:
    - master

env:
  global:
    - secure: "rBbnGfVs2g9bhAIX6hAjQMKfqT4dTEaa65sMmAp3EJUT9VVtRiRb7EtlsIy9IwLXx4w15a/myGMhDynGWzLvV+ydcKzhMgvT3dIhWm/J4noPFXT+fSPXcnAS1gPyhuMIk1cuyn5TRmvaXokihEeril/6wUHXDsfhrdMwl3A2D+OTqdaDgwj2wbTHfgmOq0uQzVBD6l3YtnmLAzo2/hdOteyy+FbWN3bjLOReh3+Xfuj2llj9OGeaSFvOe/6MASx0rkqznQ1s3t4I8Id1P9athgP51RvDFJAeY3NXPgMNAGwYObkpAz5Vywz/abX09xiDZOt4MSC+iXuKmK4OcOthrHv8CoQqnUxrCiq3hGxg+kQkAeqFuQA+iKAD3If550ABGN6AB8/uie3TZHAE6jMnHRld+ob9qvIASHbAMeIpITadqu9ceMSap5LK28zV2czSyKd2h9J2bHt3wHm5U4goP0mmV4A2LGcAH7Yo1ysl/VEYTLGrebGM0ugw2ulI+rmMxVrDEGZ8GHP7TS8mCa9lalE1HoiHkhlu0dyyFjqcLZOQGNaUykSqZjDM1v953gtOqZ2suMXnFhSSGjnlUtJrszWV22OgjNA35d2/fc2P1sMboc71zUnUVycPPy9KtyFOFuYxFWiGc23Z49KPZbbO+gYQFvuhUcpx9rPBKEEd524="

matrix:
  include:
    - os: linux
      compiler: gcc
      script: 
      - mkdir build && cd build 
      - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_FAST=OFF ..
      - make && make test
    - os: linux
      compiler: clang
      env: 
      - COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"
      - COVERITY_SCAN_BRANCH_PATTERN="master"
      - COVERITY_SCAN_NOTIFICATION_EMAIL="agievich@gmail.com"
      - COVERITY_SCAN_BUILD_COMMAND_PREPEND="cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_FAST=ON"
      - COVERITY_SCAN_BUILD_COMMAND="make"
      before_script:
      - curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash || true
    - os: linux
      compiler: gcc
      script: 
      - mkdir build && cd build 
      - cmake -DCMAKE_BUILD_TYPE=MemSan -DBUILD_FAST=OFF ..
      - make && make test
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Check BUILD_FAST=ON
      script: 
      - mkdir build && cd build 
      - cmake -DCMAKE_BUILD_TYPE=Check -DBUILD_FAST=ON ..
      - make && make test
    - os: linux
      compiler: gcc
      install:
      - gem install coveralls-lcov
      script: 
      - mkdir build && cd build 
      - cmake -DCMAKE_BUILD_TYPE=Coverage -DBUILD_FAST=OFF ..
      - make && make test
      after_success:
      - ls Testing
      - coveralls-lcov Testing/coverage.info.src
      - coveralls-lcov coverage.info.vpi
      - bash <(curl -s https://codecov.io/bash) -f Testing/coverage.info.src -f coverage.info.vpi
