# Travis-CI Build for bee2
# see travis-ci.org for details

language: c

sudo: required

branches:
  only:
    - master

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - secure: "xxx"
  matrix:
    - BUILD_TYPE=Release   BUILD_FAST=ON
    - BUILD_TYPE=Release   BUILD_FAST=OFF
    - BUILD_TYPE=Debug     BUILD_FAST=ON
    - BUILD_TYPE=Debug     BUILD_FAST=OFF
    - BUILD_TYPE=ASan      BUILD_FAST=ON
    - BUILD_TYPE=ASan      BUILD_FAST=OFF
    - BUILD_TYPE=MemSan    BUILD_FAST=ON
    - BUILD_TYPE=MemSan    BUILD_FAST=OFF
    - BUILD_TYPE=CheckFull BUILD_FAST=ON
    - BUILD_TYPE=CheckFull BUILD_FAST=OFF

matrix:
  exclude:
    - os: osx
      compiler: gcc

#addons:
#  coverity_scan:
#    project:
#      name: "agievich/bee2"
#      description: "Build submitted via Travis CI"
#      notification_email: agievich@gmail.com
#      build_command_prepend: 
#        - mkdir build-coverity && cd build-coverity
#        - cmake -DBUILD_TYPE=Debug -DBUILD_FAST=OFF ..
#      build_command: make
#      branch_pattern: master

script: 
  - mkdir build && cd build 
  - cmake -DBUILD_TYPE=$BUILD_TYPE -DBUILD_FAST=$BUILD_FAST ..
  - make
  - make test
  - sudo make install
